name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    env:
      BC_CONTAINER_NAME: bcdev
      BC_CONTAINER_USERNAME: admin
      BC_CONTAINER_PASSWORD: P@ssword1
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install -g newman
      - run: newman run "postman/Business Central API v2.0.postman_collection.json" -e "postman/BusinessCentral.postman_environment.json"